/**
 * Supabase Storage Bucket Setup
 *
 * Creates the required private storage buckets for Kira Health:
 *   - medical-documents: uploaded medical PDFs/images
 *   - report-pdfs: generated health report PDFs
 *
 * Both buckets are PRIVATE — files are accessed via signed URLs
 * generated by the backend (service role key), never exposed directly.
 *
 * Usage:
 *   cd backend
 *   npx ts-node setup-storage-buckets.ts
 *
 * Prerequisites:
 *   - SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY set in backend/.env
 */

import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

if (!supabaseUrl || !supabaseKey) {
  console.error("Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const BUCKETS = [
  {
    name: "medical-documents",
    public: false,
    allowedMimeTypes: ["application/pdf", "image/png", "image/jpeg", "image/heic"],
    fileSizeLimit: 20 * 1024 * 1024, // 20MB
  },
  {
    name: "report-pdfs",
    public: false,
    allowedMimeTypes: ["application/pdf"],
    fileSizeLimit: 10 * 1024 * 1024, // 10MB
  },
];

async function setupBuckets() {
  console.log("Setting up Supabase Storage buckets...\n");

  for (const bucket of BUCKETS) {
    // Try to get existing bucket
    const { data: existing } = await supabase.storage.getBucket(bucket.name);

    if (existing) {
      // Update existing bucket settings
      const { data, error } = await supabase.storage.updateBucket(bucket.name, {
        public: bucket.public,
        allowedMimeTypes: bucket.allowedMimeTypes,
        fileSizeLimit: bucket.fileSizeLimit,
      });

      if (error) {
        console.error(`  FAILED to update "${bucket.name}":`, error.message);
      } else {
        console.log(`  Updated "${bucket.name}" (private=${!bucket.public}, maxSize=${bucket.fileSizeLimit / 1024 / 1024}MB)`);
      }
    } else {
      // Create new bucket
      const { data, error } = await supabase.storage.createBucket(bucket.name, {
        public: bucket.public,
        allowedMimeTypes: bucket.allowedMimeTypes,
        fileSizeLimit: bucket.fileSizeLimit,
      });

      if (error) {
        console.error(`  FAILED to create "${bucket.name}":`, error.message);
      } else {
        console.log(`  Created "${bucket.name}" (private=${!bucket.public}, maxSize=${bucket.fileSizeLimit / 1024 / 1024}MB)`);
      }
    }
  }

  // Check for the old "reports" bucket that should be removed
  const { data: oldBucket } = await supabase.storage.getBucket("reports");
  if (oldBucket) {
    console.log(`\n  WARNING: Old "reports" bucket still exists.`);
    console.log(`  This bucket used the same name as the "reports" database table.`);
    console.log(`  You should migrate any files from "reports" to "report-pdfs" and then delete the old bucket.`);
    console.log(`  To delete it manually: Supabase Dashboard > Storage > reports > Delete bucket`);
  }

  console.log("\nDone.");
}

setupBuckets();
