/**
 * Supabase Storage Bucket Setup
 *
 * Creates the required private storage buckets for Kira Health:
 *   - uploads: user-uploaded medical documents (PDFs, images)
 *   - generated: system-generated reports (PDFs)
 *
 * Both buckets are PRIVATE — files are accessed via signed URLs
 * generated by the backend (service role key), never exposed directly.
 *
 * Usage:
 *   cd backend
 *   npx ts-node setup-storage-buckets.ts
 *
 * Prerequisites:
 *   - SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY set in backend/.env
 */

import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

if (!supabaseUrl || !supabaseKey) {
  console.error("Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in .env");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const BUCKETS = [
  {
    name: "uploads",
    public: false,
    allowedMimeTypes: ["application/pdf", "image/png", "image/jpeg", "image/heic"],
    fileSizeLimit: 20 * 1024 * 1024, // 20MB
  },
  {
    name: "generated",
    public: false,
    allowedMimeTypes: ["application/pdf"],
    fileSizeLimit: 10 * 1024 * 1024, // 10MB
  },
];

async function setupBuckets() {
  console.log("Setting up Supabase Storage buckets...\n");

  for (const bucket of BUCKETS) {
    // Try to get existing bucket
    const { data: existing } = await supabase.storage.getBucket(bucket.name);

    if (existing) {
      // Update existing bucket settings
      const { data, error } = await supabase.storage.updateBucket(bucket.name, {
        public: bucket.public,
        allowedMimeTypes: bucket.allowedMimeTypes,
        fileSizeLimit: bucket.fileSizeLimit,
      });

      if (error) {
        console.error(`  FAILED to update "${bucket.name}":`, error.message);
      } else {
        console.log(`  Updated "${bucket.name}" (private=${!bucket.public}, maxSize=${bucket.fileSizeLimit / 1024 / 1024}MB)`);
      }
    } else {
      // Create new bucket
      const { data, error } = await supabase.storage.createBucket(bucket.name, {
        public: bucket.public,
        allowedMimeTypes: bucket.allowedMimeTypes,
        fileSizeLimit: bucket.fileSizeLimit,
      });

      if (error) {
        console.error(`  FAILED to create "${bucket.name}":`, error.message);
      } else {
        console.log(`  Created "${bucket.name}" (private=${!bucket.public}, maxSize=${bucket.fileSizeLimit / 1024 / 1024}MB)`);
      }
    }
  }

  // Check for old buckets that should be removed
  for (const oldName of ["reports", "report-pdfs", "medical-documents"]) {
    const { data: oldBucket } = await supabase.storage.getBucket(oldName);
    if (oldBucket) {
      console.log(`\n  WARNING: Old "${oldName}" bucket still exists.`);
      console.log(`  Migrate any files to the new buckets ("uploads" / "generated") and delete it.`);
      console.log(`  To delete: Supabase Dashboard > Storage > ${oldName} > Delete bucket`);
    }
  }

  console.log("\nDone.");
}

setupBuckets();
